### ISSUE TITLE
Request: make extension available for safari?

### ISSUE THREAD

**Issue by charlottetan** [rubenmv/extension-goodreads-ratings-for-amazon#3]
Thanks for considering!

**Comment by rubenmv** [comment]
Hi! I know nothing about safari extensions but I'll try this weekend and see if I can do something.

**Comment by rubenmv** [comment]
I've been looking into this and I'm sorry to tell you that it is not possible right now for me to port this extension to Safari since it requires a Mac machine (which I don't have), and an Apple Developer account (which is not free or even cheap), plus I would need to rewrite and maintain a separate extension just for this (although I wouldn't mind doing it since this is a small one).
